[package]
name = "genealogy"
version = "0.1.1"
description = "祖谱软件"
authors = ["mugbya"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "genealogy_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "fs"] }
rusqlite = { version = "0.31", features = ["bundled"] }
argon2 = "0.5"
jsonwebtoken = "9"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
sysinfo = "0.32"
if-addrs = "0.14"
calamine = "0.26"
mime = "0.3"
base64 = "0.21"
reqwest = { version = "0.12", features = ["json", "blocking"] }
urlencoding = "2"
uuid = { version = "1", features = ["v4"] }

